### ISSUE TITLE
DockerHub build failed at conda env create command with connection broken error

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/PAVICS-e2e-workflow-tests#51]
Been failing since 3 days on DockerHub.  Manual build on my own VM is fine.

Build logs [docker-hub-build-log-error.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5256267/docker-hub-build-log-error.txt), matching link https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/2814f456-2193-4bc7-9477-164f364c4868

![Screenshot_2020-09-21 Docker Hub(1)](https://user-images.githubusercontent.com/11966697/93783634-ec69b300-fbf9-11ea-9449-72d4a3ae02ab.png)

**Comment by tlvu** [comment]
Might relate to old DockerHub build problem https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/33

**Comment by rdemonteiro** [comment]
Salut Long
Pourrais-tu m’appeler 514 291 7228
Je suis un peu perdu avec cet achat je ne trouve pas exactement ce que tu as toi avec tes screenshoots
Merci
Romy

De : Long Vu <notifications@github.com>
Envoyé : 21 septembre 2020 11:12
À : Ouranosinc/PAVICS-e2e-workflow-tests <PAVICS-e2e-workflow-tests@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Ouranosinc/PAVICS-e2e-workflow-tests] DockerHub build failed at conda env create command with connection broken error (#51)


Been failing since 3 days on DockerHub. Manual build on my own VM is fine.

Build logs docker-hub-build-log-error.txt<https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5256267/docker-hub-build-log-error.txt>, matching link https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/2814f456-2193-4bc7-9477-164f364c4868

[Screenshot_2020-09-21 Docker Hub(1)]<https://user-images.githubusercontent.com/11966697/93783634-ec69b300-fbf9-11ea-9449-72d4a3ae02ab.png>

**Comment by tlvu** [comment]
Support ticket opened for DockerHub, no reply:

-------- Original Message --------
From: Support <hub-support@docker.com>
Subject: Docker Support [Request received] - Build failing on DockerHub (#21482)
Date: Wednesday, November 11, 2020, 16:52 EST

**Comment by tlvu** [comment]
Fixed by https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95
