### ISSUE TITLE
Workflow repo reference mismatch with instance

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/PAVICS-e2e-workflow-tests#58]
Our Jenkins triggered an error due to mismatches between versions: 

http://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/master/138/console

In summary, because `finch` version is pinned : 

https://github.com/bird-house/birdhouse-deploy/blob/fb5ac36f4ea6a48bb729e14ce5fbee681cc1fdad/birdhouse/default.env#L7

Whereas the E2E test suite targets master by default: 

https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/18c8397ff30c9ba4b9f56896df4c898c7e9a356e/default_build_params#L29-L34

Any recent change to master such as this one breaks the test-suite: 

https://github.com/bird-house/finch/commit/8c23a9c161d4b7e5da1691d0fc6279740f4da59d

I feel like the default values should be adjusted to reflect current image version instead of master (should be synced with bird-hose/birdhouse-deploy tags) to avoid any repo change to always fail the whole test-suite.

**Comment by tlvu** [comment]
@fmigneault We've decided to always test against the latest notebooks since these are the notebooks that are autodeployed to PAVICS so we test what we actually deploy.  If a bird or component needs to be up-to-date, we'll release it.

I already caught it yesterday (https://github.com/bird-house/finch/pull/133#discussion_r556052565) right after the offending PR is merged.

A new finch is already underway (PR https://github.com/bird-house/finch/pull/138).

Pinning the notebooks means if there are notebooks update between 2 finch releases, we have to do special work to get it out, I'd rather not make the process more laborious.

The current way, we force continuous release of the birds.  I'd much prefer that.

We can review this strategy if the breakage frequency is much higher than currently.

I'll let you close this issue.
