### ISSUE TITLE
Intermittent warnings "Unable to revert mtime: /opt/conda/envs/birdy/fonts" confuse new Jupyter users

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/PAVICS-e2e-workflow-tests#97]
This warning happens only in "interactive" mode when a real user uses the Jupyter env in a browser.  During nightly Jenkins unattended run, it does not happen.

The warning appears only once and may or may not re-appear again after a "Restart kernel".  It is completely intermittent.

FYI @huard

**Comment by tlvu** [comment]
@huard @richardarsenault I might possibly have a fix for this intermittent warning "Unable to revert mtime: /opt/conda/envs/birdy/fonts".

I need to test my fix.  Do you happen to remember which Raven notebooks the warning was showing up?  This do not happen during Jenkins automated test so I have to reproduce this live, in a Jupyter env.

**Comment by richardarsenault** [comment]
@tlvu From what I understand, the first notebook (01_intorduction_to_ravenpy) was one of the culprits, but it only happened to a few (maybe 10?) participants out of the 50 that were attending at the time. When they re-ran the cells, it worked again. So I fear it is related to the server being overwhelmed somehow, and that it will not be so easy to reproduce. I was a bit busy explaining things but Perhaps @huard and @cjauvin have more insight since they were more in the "debugging" mode.

**Comment by tlvu** [comment]
Weird enough I was not able to reproduce this problem with our current Jupyter env.  I was able to reproduce before.  This seems to be very intermittent.

I attempted a blind fix in https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/101.  Hopefully it works.  If not, re-open this issue.
